### PR TITLE
Update django 2.2

### PR DESCRIPTION
**Pull request by rmader**
This is a huge update in various areas. I still need to reorder the commits a bit for later, otherwise this is ready for review. Needs a lot of manual testing I guess.

### CODE REVIEW

**Comment by rmader** [comment]
Arght, that's to many changes, not really worth to split them into individual commits in this project.

**Review by fuzzylogic2000 — DISMISSED** [review]
The font awesome in the teasers block is broken.
I can't use the calendar's block, because it will not show me the blog page as a block page?

**Comment by fuzzylogic2000** [comment]
Nice, that you put all the updates and changes in, that happened in the other projects inbetween!

**Comment by rmader** [comment]
Fixed fontawesome, can't test the calendar. As it's not currently planned to use it -> merging

**Pull request merged**
